name: Go Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build-and-run:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: C:\Users\hadyi\Documents\coding\formula\selfhostedrunner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Echo workspace
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE

      # - name: Build
      #   run: |
      #     cd ../formula/selfhostedrunner
      #     pwd
      #     go build

      

      # - name: Print Directory Contents
      #   run: ls -R  # This will list the contents of the current working directory (repository root)

      - name: Build
        run: |
          pwd
          go build

      - name: Run Executable
        run: ./selfhostedrunner.exe
        # run: |
        #   cd ../formula/selfhostedrunner
        #   ./selfhostedrunner.exe

      # - name: Cleanup
      #   if: always()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: test-results
      #     path: app/build
