name: Go Build and Run

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        working-directory: C:\Users\hadyi\Documents\coding\formula\selfhostedrunner
        run: |
          cd C:\Users\hadyi\Documents\coding\formula\selfhostedrunner && pwd
          cd C:\Users\hadyi\Documents\coding\formula\selfhostedrunner && go build

      - name: Run Executable
        working-directory: C:\Users\hadyi\Documents\coding\formula\selfhostedrunner
        run: ./selfhostedrunner.exe
