name: Go Build and Run

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: C:\Users\hadyi\Documents\coding\formula\selfhostedrunner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          pwd
          go build

      - name: Run Executable
        run: ./selfhostedrunner.exe
