name: Go Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build-and-run:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Echo workspace
        run: |
          echo 'test'
          echo ${{ github.workspace }}

      - name: Build
        run: |
          pwd
          cd ${{ github.workspace }}
          go build

      - name: Run Executable
        run: |
          cd ${{ github.workspace }}
          ./selfhostedrunner.exe

      # - name: Cleanup
      #   if: success() || failure()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: test-results
      #     path: app/build
